import React from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { CheckCircle2, AlertCircle, LayoutDashboard, RefreshCw, ChevronRight } from 'lucide-react';

const ResultPage = () => {
  const navigate = useNavigate();
  const location = useLocation();

  // --- STRICT CRASH PREVENTION ---
  // Access data safely from router state
  const data = location.state;

  // Fallback if no data is provided (direct access prevention)
  if (!data) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900 p-6">
        <div className="w-full max-w-md bg-white dark:bg-gray-800 rounded-3xl p-8 shadow-xl border border-gray-100 dark:border-gray-700 text-center">
          <div className="flex justify-center mb-6">
            <div className="p-4 bg-orange-50 dark:bg-orange-900/20 text-orange-500 rounded-full">
              <AlertCircle size={48} />
            </div>
          </div>
          <h1 className="text-2xl font-bold mb-2">No result available</h1>
          <p className="text-gray-500 dark:text-gray-400 mb-8">
            Please perform an analysis to see your results.
          </p>
          <button 
            onClick={() => navigate('/dashboard')}
            className="w-full py-3 bg-blue-600 text-white rounded-xl font-bold shadow-lg hover:bg-blue-700 transition-all"
          >
            Go to Dashboard
          </button>
        </div>
      </div>
    );
  }

  // Fallback values for stability
  const resultStatus = data?.status || "Unknown";
  const confidence = data?.confidence || 0;
  const isHealthy = resultStatus === "Healthy";

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900 p-4 sm:p-6 lg:p-8 animate-in fade-in duration-700">
      <div className="w-full max-w-lg bg-white dark:bg-gray-800 rounded-[2rem] shadow-2xl border border-gray-100 dark:border-gray-700 overflow-hidden transform transition-all hover:shadow-3xl">
        {/* Header */}
        <div className="p-8 text-center border-b border-gray-50 dark:border-gray-700 bg-white dark:bg-gray-800/50">
          <h1 className="text-2xl sm:text-3xl font-black tracking-tight text-gray-900 dark:text-white">
            Analysis Result
          </h1>
          <p className="mt-2 text-sm font-medium text-gray-500 dark:text-gray-400">
            Based on our AI-powered acoustic analysis
          </p>
        </div>

        {/* Content */}
        <div className="p-8 sm:p-10 space-y-10">
          {/* Main Status Circle */}
          <div className="flex flex-col items-center">
            <div className={`relative p-1 rounded-full mb-6 ${isHealthy ? 'bg-emerald-50 content-[""]' : 'bg-red-50'}`}>
              <div className={`p-6 rounded-full ${isHealthy ? 'bg-emerald-500 text-white shadow-emerald-200' : 'bg-red-500 text-white shadow-red-200'} shadow-xl`}>
                {isHealthy ? <CheckCircle2 size={56} strokeWidth={2.5} /> : <AlertCircle size={56} strokeWidth={2.5} />}
              </div>
            </div>
            
            <h2 className={`text-4xl font-black mb-2 tracking-tighter ${isHealthy ? 'text-emerald-600 dark:text-emerald-400' : 'text-red-600 dark:text-red-400'}`}>
              {resultStatus}
            </h2>
            <div className={`px-4 py-1 rounded-full text-xs font-bold uppercase tracking-widest ${isHealthy ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-700'}`}>
              Condition Detected
            </div>
          </div>

          {/* Confidence Score Section */}
          <div className="space-y-4">
            <div className="flex justify-between items-end mb-1">
              <span className="text-sm font-bold text-gray-500 dark:text-gray-400">Acoustic Confidence</span>
              <span className="text-2xl font-black text-gray-900 dark:text-white">{confidence}%</span>
            </div>
            
            {/* Simple Progress Bar */}
            <div className="h-4 w-full bg-gray-100 dark:bg-gray-700 rounded-full overflow-hidden p-1">
              <div 
                className={`h-full rounded-full transition-all duration-1000 ease-out ${isHealthy ? 'bg-emerald-500 shadow-[0_0_10px_rgba(16,185,129,0.3)]' : 'bg-red-500 shadow-[0_0_10px_rgba(239,68,68,0.3)]'}`}
                style={{ width: `${confidence}%` }}
              />
            </div>
            <p className="text-[10px] text-center text-gray-400 font-medium">
              This result is generated by AI patterns. For a medical diagnosis, please consult a healthcare professional.
            </p>
          </div>

          {/* Action Buttons */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-4">
            <button
              onClick={() => navigate('/analyze')}
              className="flex items-center justify-center gap-2 px-6 py-4 rounded-2xl font-bold bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 hover:bg-blue-100 dark:hover:bg-blue-900/50 transition-all border border-blue-100 dark:border-blue-900/30 active:scale-95"
            >
              <RefreshCw size={18} />
              Analyze Again
            </button>
            <button
              onClick={() => navigate('/dashboard')}
              className="group flex items-center justify-center gap-2 px-6 py-4 rounded-2xl font-bold bg-blue-600 text-white shadow-xl shadow-blue-200/50 dark:shadow-none hover:bg-blue-700 hover:scale-[1.02] transition-all active:scale-95"
            >
              <LayoutDashboard size={18} />
              Dashboard
              <ChevronRight size={18} className="group-hover:translate-x-1 transition-transform" />
            </button>
          </div>
        </div>

        {/* Footer Accent */}
        <div className={`h-2 w-full ${isHealthy ? 'bg-emerald-500' : 'bg-red-500'} opacity-50`} />
      </div>
    </div>
  );
};

export default ResultPage;
